[2025-03-17T07:05:18.171+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-17T07:05:18.189+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_branch_operator.ext_py_b scheduled__2025-03-16T00:00:00+00:00 [queued]>
[2025-03-17T07:05:18.199+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_branch_operator.ext_py_b scheduled__2025-03-16T00:00:00+00:00 [queued]>
[2025-03-17T07:05:18.200+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-03-17T07:05:18.214+0000] {taskinstance.py:2889} INFO - Executing <Task(ExternalPythonOperator): ext_py_b> on 2025-03-16 00:00:00+00:00
[2025-03-17T07:05:18.222+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=140) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-17T07:05:18.224+0000] {standard_task_runner.py:72} INFO - Started process 143 to run task
[2025-03-17T07:05:18.224+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'example_branch_operator', 'ext_py_b', 'scheduled__2025-03-16T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', '/home/***/.local/lib/python3.12/site-packages/***/example_dags/example_branch_operator.py', '--cfg-path', '/tmp/tmp_aq26fig']
[2025-03-17T07:05:18.225+0000] {standard_task_runner.py:105} INFO - Job 19: Subtask ext_py_b
[2025-03-17T07:05:18.266+0000] {task_command.py:467} INFO - Running <TaskInstance: example_branch_operator.ext_py_b scheduled__2025-03-16T00:00:00+00:00 [running]> on host 758401fd595f
[2025-03-17T07:05:18.339+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_branch_operator' AIRFLOW_CTX_TASK_ID='ext_py_b' AIRFLOW_CTX_EXECUTION_DATE='2025-03-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-16T00:00:00+00:00'
[2025-03-17T07:05:18.341+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-17T07:05:18.341+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-17T07:05:18.341+0000] {logging_mixin.py:190} INFO - Current task name:ext_py_b state:running start_date:2025-03-17 07:05:18.190224+00:00
[2025-03-17T07:05:18.342+0000] {logging_mixin.py:190} INFO - Dag name:example_branch_operator and current dag run status:running
[2025-03-17T07:05:18.342+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-17T07:05:18.629+0000] {baseoperator.py:416} WARNING - ExternalPythonOperator.execute cannot be called outside TaskInstance!
[2025-03-17T07:05:18.667+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python /tmp/venv-callokk9k_b5/script.py /tmp/venv-callokk9k_b5/script.in /tmp/venv-callokk9k_b5/script.out /tmp/venv-callokk9k_b5/string_args.txt /tmp/venv-callokk9k_b5/termination.log
[2025-03-17T07:05:18.668+0000] {process_utils.py:190} INFO - Output:
[2025-03-17T07:05:20.005+0000] {process_utils.py:194} INFO - /home/***/.local/lib/python3.12/site-packages/***/configuration.py:859 FutureWarning: section/key [core/sql_alchemy_conn] has been deprecated, you should use[database/sql_alchemy_conn] instead. Please update your `conf.get*` call to use the new name
[2025-03-17T07:05:20.971+0000] {process_utils.py:194} INFO - Hello World from external Python
[2025-03-17T07:05:21.263+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-17T07:05:21.273+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-17T07:05:21.273+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=example_branch_operator, task_id=ext_py_b, run_id=scheduled__2025-03-16T00:00:00+00:00, execution_date=20250316T000000, start_date=20250317T070518, end_date=20250317T070521
[2025-03-17T07:05:21.282+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-17T07:05:21.282+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-17T07:05:21.283+0000] {logging_mixin.py:190} INFO - Dag name:example_branch_operator queued_at:2025-03-17 07:05:02.957069+00:00
[2025-03-17T07:05:21.283+0000] {logging_mixin.py:190} INFO - Task hostname:758401fd595f operator:ExternalPythonOperator
[2025-03-17T07:05:21.331+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-17T07:05:21.351+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-17T07:05:21.353+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
